name: Frontend Update

on:
  push:
    branches:
      - main

jobs:
  deploy_pipe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: yarn install
        working-directory: ./portfolio_front
        run: yarn install
      - name: lint
        working-directory: ./portfolio_front
        run: yarn lint
      - name: test
        working-directory: ./portfolio_front
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
