name: Frontend Update

on:
  push:
    branches:
      - main

jobs:
  deploy_pipe:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./portfolio_front
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
      - name: test
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./portfolio_front
          start: yarn start
          wait-on: http://localhost:3000
